# Generated by Django 5.2.17 on 2026-09-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('svg_key', models.CharField(max_length=50)),
                ('viewbox_width', models.PositiveIntegerField(default=200)),
                ('viewbox_height', models.PositiveIntegerField(default=220)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GarmentStyleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SlugField()),
                ('category_label', models.CharField(max_length=50)),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=50)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_options', to='catalog.garmenttype')),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
                'unique_together': {('garment_type', 'category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PrintZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('dpi', models.PositiveIntegerField(default=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_zones', to='catalog.garmenttype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('garment_type', 'key')},
            },
        ),
    ]
