# Generated by Django 5.2.17 on 2026-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmenttype',
            name='category',
            field=models.CharField(choices=[('tees', 'T-Shirts & Tops'), ('shirts', 'Shirts & Polos'), ('sweats', 'Hoodies & Sweatshirts'), ('outerwear', 'Jackets & Outerwear'), ('ethnic', 'Indian & Ethnic Wear'), ('dresses', 'Dresses & Sets'), ('accessories', 'Accessories')], default='tees', max_length=20),
        ),
        migrations.AddField(
            model_name='garmenttype',
            name='department',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='garmenttype',
            name='viewbox_height',
            field=models.PositiveIntegerField(default=280),
        ),
    ]
