# Generated by Django 5.2.17 on 2026-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Shown in the public template gallery for others to clone.'),
        ),
        migrations.AddField(
            model_name='uploadedasset',
            name='dominant_colors',
            field=models.JSONField(blank=True, default=list, help_text='Hex colors from k-means clustering of the artwork.'),
        ),
        migrations.AddField(
            model_name='uploadedasset',
            name='suggested_print_method',
            field=models.CharField(blank=True, choices=[('one_color', '1-Color Screen Print'), ('spot_color', 'Multi-Color Screen Print'), ('full_color', 'Full-Color DTG')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedasset',
            name='vector_image',
            field=models.FileField(blank=True, null=True, upload_to='designer/vectors/'),
        ),
    ]
